/* Deterministic PNG-to-H.264 exporter adapted from AcademyWizard's recorder.
   Each HTML document owns one finite master timeline; no wall-clock capture.
   Run: node animations/enhanced/render_videos.cjs [asset ...]
   Optional: NODE_PATH, CHROMIUM_PATH, FFMPEG_BIN, VIDEO_QA_DIR. */
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),{spawn}=require('child_process'),{once}=require('events');
const pw=require('playwright');
const root=path.resolve(__dirname,'../..'),data=JSON.parse(fs.readFileSync(__dirname+'/storyboards.json'));const names=process.argv.slice(2),queue=data.filter(d=>!d.static&&(!names.length||names.includes(d.asset)));
const qa=process.env.VIDEO_QA_DIR||path.resolve(root,'../../../build/lvdc-video-qa');fs.mkdirSync(qa,{recursive:true});
const ff=process.env.FFMPEG_BIN||'ffmpeg',fps=24,scale=1.5;
(async()=>{const browser=await pw.chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || undefined});let report=[];
async function worker(){for(;;){const d=queue.shift();if(!d)return;const page=await browser.newPage({viewport:{width:1920,height:900},deviceScaleFactor:scale});await page.goto(pathToFileURL(root+'/animations/'+d.asset+'.html').href);await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>renderAtTime(0));
const output=root+'/figures/'+d.asset+'.mp4',temp=output+'.pending.mp4';const enc=spawn(ff,['-hide_banner','-y','-f','image2pipe','-vcodec','png','-framerate',String(fps),'-i','pipe:0','-an','-vf','scale=in_range=full:out_range=limited:out_color_matrix=bt709,format=yuv420p','-color_range','tv','-c:v','libx264','-preset','medium','-tune','animation','-crf','8','-pix_fmt','yuv420p','-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709','-movflags','+faststart',temp],{stdio:['pipe','ignore','pipe']});let error='';enc.stderr.on('data',s=>{error=(error+s).slice(-5000)});const closed=once(enc,'close');const count=Math.ceil(d.duration*fps);let old='',buffer=null,unique=0;
for(let i=0;i<count;i++){const t=i/fps;const svg=await page.evaluate(ms=>{renderAtTime(ms);return document.querySelector('svg').outerHTML},t*1000);if(svg!==old){buffer=await page.screenshot({type:'png'});old=svg;unique++;}if(!enc.stdin.write(buffer))await once(enc.stdin,'drain');if(i&&i%720===0)console.log(d.asset,Math.round(i/count*100)+'%')}enc.stdin.end();let [code]=await closed;if(code)throw Error(error);fs.renameSync(temp,output);
const times=[0,d.duration*.25,d.duration*.5,d.duration*.75,d.duration-1/fps,...d.chapters.slice(1).flatMap(c=>[c.start-1/fps,c.start+1/fps])];const folder=qa+'/'+d.asset;fs.mkdirSync(folder,{recursive:true});for(let j=0;j<times.length;j++){await page.evaluate(ms=>renderAtTime(ms),Math.max(0,times[j])*1000);await page.screenshot({path:folder+'/source_'+j+'.png'});}
const poster=d.chapters[2].start+(d.chapters[2].end-d.chapters[2].start)*.72;await page.evaluate(ms=>renderAtTime(ms),poster*1000);await page.screenshot({path:root+'/figures/'+d.asset+'_poster.png'});await page.close();const item={asset:d.asset,duration:count/fps,narration:d.duration,fps,width:2880,height:1350,frames:count,uniqueFrames:unique,poster,times,bytes:fs.statSync(output).size};fs.writeFileSync(folder+'/encoding.json',JSON.stringify(item,null,2));report.push(item);console.log('COMPLETE',d.asset,(count/fps).toFixed(3)+'s',unique+' distinct frames');}}
await Promise.all([worker(),worker()]);await browser.close();fs.writeFileSync(qa+'/encoding_latest.json',JSON.stringify(report,null,2));})();
